### ISSUE TITLE
Known implementations

### ISSUE THREAD

**Issue by brimcfadden** [tuupola/branca-spec#12]
The known implementations in the readme are links to libsodium implementations, not branca ones.

https://github.com/tuupola/branca-spec/blob/b1ecd47ae7eb27b86f50cb72b47ab90b1f5b3bfd/README.md#libraries

**Comment by tuupola** [comment]
If you click "Elixir" it will go to the Elixir implementation. If you click "Go" it will go to the Go implementation. Next to those links is also a link to the crypto library which this implementation uses. Usually libsodium because it can be considered the best.
