### ISSUE TITLE
Another one Golang implementation for Branca

### ISSUE THREAD

**Issue by andyone** [tuupola/branca-spec#17]
Hi! We have been released our high-grade quality package with Branca implementation - https://github.com/essentialkaos/branca

Features:
- Pure Go implementation;
- No third-party dependencies at all;
- 100% code coverage;
- Fuzz tests.

I think it will be great to add information about this package to the branca website.

**Comment by tuupola** [comment]
Looks great! Will add links.

**Comment by tuupola** [comment]
Added. Thanks!
