### ISSUE TITLE
Base62 is actually Base61

### ISSUE THREAD

**Issue by johnaoss** [tuupola/branca-spec#22]
The character set provided in the spec: 
```
0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxy
```
Only contains 61 characters, and is thus a base61 encoding. Looking at the implementations listed on the document, it seems that most of them (if not all) include a `z` to the character set as I would expect.

Is this the intended behaviour? Or should the character set not include the character `z`?

**Comment by tuupola** [comment]
You are correct. Seems to be copy paste error. The `z` is missing. It should be `0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz`.

**Comment by tuupola** [comment]
Thanks for the heads up!
