### ISSUE TITLE
Python implementation

### ISSUE THREAD

**Issue by tuupola** [tuupola/branca-spec#4]
Python implementation is badly needed. Something similar as [pyjwt](https://github.com/jpadilla/pyjwt) by @jpadilla. Anyone interested in implementing it write me a note here and I will add it to the docs.

**Comment by DragosDumitrache** [comment]
This sounds like fun, mind if I give it a go?

**Comment by tuupola** [comment]
Sure! When you setup the GitHub repository post a link here so I can link it as Work In Progress from the docs.

**Comment by tuupola** [comment]
One implementation is available at [tuupola/branca-python]( https://github.com/tuupola/branca-python). Alternative implementations welcome!
