### ISSUE TITLE
WARNING PHISHING ATTEMPT

### ISSUE THREAD

**Issue by kiwifellows** [tuupola/branca-spec#46]
Hi, 
beware of a phising attempt from a previous message coming through appearing to be genuine.

The title is "IMPORTANT! Security Vulnerability Detected in your Repository"

IGNORE THIS BECAUSE it has a suspect external url that goes to an external website asking users to cut and paste sensitive information.

**Comment by tuupola** [comment]
Not sure which message you mean?

**Comment by tuupola** [comment]
Now I see. I had the message in email only. Thanks for the heads up!
