### ISSUE TITLE
Erlang implementation

### ISSUE THREAD

**Issue by tuupola** [tuupola/branca-spec#9]
Erlang implementation is missing. Something similar as [fernet-erl](https://github.com/fernet/fernet-erl) by @bigkevmcd. Anyone interested in implementing it write me a note here and I will add it to the docs.

**Comment by tuupola** [comment]
Excellent!

**Comment by 1ma** [comment]
It's done https://github.com/1ma/branca-erl

**Comment by tuupola** [comment]
Super. Thanks!
